---
#Basic update and firewall tasks in all clients
- hosts: all
  become: 'yes'
  roles:
    - dnf_automatic
    - firewall_exceptions
    - selinux
    
#Apache deploy to new webservers
- hosts: webservers 1
  become: 'yes'
  roles:
    - apache
    
#HAproxy tasks in Loadbalancer
- hosts: loadbalancer
  become: 'yes'
  roles:
    - haproxy

#Siege tasks in Siege host
- hosts: siege
  become: 'yes'
  roles:
    - siege
